In [117]:
import numpy as np
import torch
import plotly.express as px

In [118]:
KNOT_U = torch.tensor([0.0, 0.0, 0.0, 0.3333333333333333, 0.6666666666666666, 1.0, 1.0, 1.0])
knots_v = torch.tensor([0.0, 0.0, 0.0, 0.16666666666666666, 0.3333333333333333, 0.5, 0.6666666666666666, 0.8333333333333334, 1.0, 1.0, 1.0])

control_points_flat = torch.tensor([
    [0.0000, 0.0000, -1.0000, 1.0000],
    [-1.0000, 0.0000, -1.0000, 0.7071],
    [-1.0000, 0.0000, 0.0000, 1.0000],
    [-1.0000, 0.0000, 1.0000, 0.7071],
    [0.0000, 0.0000, 1.0000, 1.0000],
    [0.0000, 0.0000, -1.0000, 0.7071],
    [-1.0000, -1.0000, -1.0000, 0.5000],
    [-1.0000, -1.0000, 0.0000, 0.7071],
    [-1.0000, -1.0000, 1.0000, 0.5000],
    [0.0000, 0.0000, 1.0000, 0.7071],
    [0.0000, 0.0000, -1.0000, 1.0000],
    [0.0000, -1.0000, -1.0000, 0.7071],
    [0.0000, -1.0000, 0.0000, 1.0000],
    [0.0000, -1.0000, 1.0000, 0.7071],
    [0.0000, 0.0000, 1.0000, 1.0000],
    [0.0000, 0.0000, -1.0000, 0.7071],
    [1.0000, -1.0000, -1.0000, 0.5000],
    [1.0000, -1.0000, 0.0000, 0.7071],
    [1.0000, -1.0000, 1.0000, 0.5000],
    [0.0000, 0.0000, 1.0000, 0.7071],
    [0.0000, 0.0000, -1.0000, 1.0000],
    [1.0000, 0.0000, -1.0000, 0.7071],
    [1.0000, 0.0000, 0.0000, 1.0000],
    [1.0000, 0.0000, 1.0000, 0.7071],
    [0.0000, 0.0000, 1.0000, 1.0000],
    [0.0000, 0.0000, -1.0000, 0.7071],
    [1.0000, 1.0000, -1.0000, 0.5000],
    [1.0000, 1.0000, 0.0000, 0.7071],
    [1.0000, 1.0000, 1.0000, 0.5000],
    [0.0000, 0.0000, 1.0000, 0.7071],
    [0.0000, 0.0000, -1.0000, 1.0000],
    [0.0000, 1.0000, -1.0000, 0.7071],
    [0.0000, 1.0000, 0.0000, 1.0000],
    [0.0000, 1.0000, 1.0000, 0.7071],
    [0.0000, 0.0000, 1.0000, 1.0000],
    [0.0000, 0.0000, -1.0000, 0.7071],
    [-1.0000, 1.0000, -1.0000, 0.5000],
    [-1.0000, 1.0000, 0.0000, 0.7071],
    [-1.0000, 1.0000, 1.0000, 0.5000],
    [0.0000, 0.0000, 1.0000, 0.7071],
])

In [119]:
control_points_flat

tensor([[ 0.0000,  0.0000, -1.0000,  1.0000],
        [-1.0000,  0.0000, -1.0000,  0.7071],
        [-1.0000,  0.0000,  0.0000,  1.0000],
        [-1.0000,  0.0000,  1.0000,  0.7071],
        [ 0.0000,  0.0000,  1.0000,  1.0000],
        [ 0.0000,  0.0000, -1.0000,  0.7071],
        [-1.0000, -1.0000, -1.0000,  0.5000],
        [-1.0000, -1.0000,  0.0000,  0.7071],
        [-1.0000, -1.0000,  1.0000,  0.5000],
        [ 0.0000,  0.0000,  1.0000,  0.7071],
        [ 0.0000,  0.0000, -1.0000,  1.0000],
        [ 0.0000, -1.0000, -1.0000,  0.7071],
        [ 0.0000, -1.0000,  0.0000,  1.0000],
        [ 0.0000, -1.0000,  1.0000,  0.7071],
        [ 0.0000,  0.0000,  1.0000,  1.0000],
        [ 0.0000,  0.0000, -1.0000,  0.7071],
        [ 1.0000, -1.0000, -1.0000,  0.5000],
        [ 1.0000, -1.0000,  0.0000,  0.7071],
        [ 1.0000, -1.0000,  1.0000,  0.5000],
        [ 0.0000,  0.0000,  1.0000,  0.7071],
        [ 0.0000,  0.0000, -1.0000,  1.0000],
        [ 1.0000,  0.0000, -1.0000

In [120]:
coordinate = control_points_flat[:, :-1]
coordinate = np.unique(coordinate, axis=0)
coordinate

array([[-1., -1., -1.],
       [-1., -1.,  0.],
       [-1., -1.,  1.],
       [-1.,  0., -1.],
       [-1.,  0.,  0.],
       [-1.,  0.,  1.],
       [-1.,  1., -1.],
       [-1.,  1.,  0.],
       [-1.,  1.,  1.],
       [ 0., -1., -1.],
       [ 0., -1.,  0.],
       [ 0., -1.,  1.],
       [ 0.,  0., -1.],
       [ 0.,  0.,  1.],
       [ 0.,  1., -1.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  1.],
       [ 1., -1., -1.],
       [ 1., -1.,  0.],
       [ 1., -1.,  1.],
       [ 1.,  0., -1.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  1.],
       [ 1.,  1., -1.],
       [ 1.,  1.,  0.],
       [ 1.,  1.,  1.]], dtype=float32)

In [121]:
fig = px.scatter_3d(coordinate, x=0, y=1, z=2)
fig.show()

In [122]:
u = torch.linspace(0, 1, 10).T.unsqueeze(-1)
u

tensor([[0.0000],
        [0.1111],
        [0.2222],
        [0.3333],
        [0.4444],
        [0.5556],
        [0.6667],
        [0.7778],
        [0.8889],
        [1.0000]])

In [123]:
knots_u = KNOT_U.unsqueeze(0)
knots_u

tensor([[0.0000, 0.0000, 0.0000, 0.3333, 0.6667, 1.0000, 1.0000, 1.0000]])

In [124]:
u >= knots_u

tensor([[ True,  True,  True, False, False, False, False, False],
        [ True,  True,  True, False, False, False, False, False],
        [ True,  True,  True, False, False, False, False, False],
        [ True,  True,  True,  True, False, False, False, False],
        [ True,  True,  True,  True, False, False, False, False],
        [ True,  True,  True,  True, False, False, False, False],
        [ True,  True,  True,  True, False, False, False, False],
        [ True,  True,  True,  True,  True, False, False, False],
        [ True,  True,  True,  True,  True, False, False, False],
        [ True,  True,  True,  True,  True,  True,  True,  True]])

In [125]:
lower_bound_u = knots_u[..., :-1]
upper_bound_u = knots_u[..., 1:]

epsilon = 1e-6
max_val = knots_u.max() - epsilon
u_clamped = torch.min(u, max_val)

b_u = ((u_clamped >= lower_bound_u) & (u_clamped < upper_bound_u)).float()
b_u

tensor([[0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0.]])

In [126]:
degree = 2

In [127]:
def divide(numerator, denominator, thresh = 1e-6):
    return torch.where(denominator.abs() < thresh, torch.zeros_like(numerator), numerator / denominator)

In [128]:

for d in range(1, degree + 1):
    b_u = divide((u - knots_u[..., :-(d + 1)]), (knots_u[..., d:-1] - knots_u[..., :-(d + 1)])) * b_u[..., :-1] + divide((knots_u[..., (d + 1):] - u), (knots_u[..., (d + 1):] - knots_u[..., 1: -d])) * b_u[..., 1:]

b_u

tensor([[1.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [4.4444e-01, 5.0000e-01, 5.5556e-02, 0.0000e+00, 0.0000e+00],
        [1.1111e-01, 6.6667e-01, 2.2222e-01, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 5.0000e-01, 5.0000e-01, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 2.2222e-01, 7.2222e-01, 5.5556e-02, 0.0000e+00],
        [0.0000e+00, 5.5556e-02, 7.2222e-01, 2.2222e-01, 0.0000e+00],
        [0.0000e+00, 1.5987e-14, 5.0000e-01, 5.0000e-01, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 2.2222e-01, 6.6667e-01, 1.1111e-01],
        [0.0000e+00, 0.0000e+00, 5.5556e-02, 5.0000e-01, 4.4444e-01],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 1.0000e+00]])

In [129]:
v = torch.linspace(0, 1, 15).T.unsqueeze(-1)
v

tensor([[0.0000],
        [0.0714],
        [0.1429],
        [0.2143],
        [0.2857],
        [0.3571],
        [0.4286],
        [0.5000],
        [0.5714],
        [0.6429],
        [0.7143],
        [0.7857],
        [0.8571],
        [0.9286],
        [1.0000]])

In [130]:
lower_bound_v = knots_v[..., :-1]
upper_bound_v = knots_v[..., 1:]

epsilon = 1e-6
max_val = knots_v.max() - epsilon
v_clamped = torch.min(v, max_val)

b_v = ((v_clamped >= lower_bound_v) & (v_clamped < upper_bound_v)).float()
b_v

tensor([[0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.]])

In [131]:
for d in range(1, degree + 1):
    b_v = divide((v - knots_v[..., :-(d + 1)]), (knots_v[..., d:-1] - knots_v[..., :-(d + 1)])) * b_v[..., :-1] + divide((knots_v[..., (d + 1):] - v), (knots_v[..., (d + 1):] - knots_v[..., 1: -d])) * b_v[..., 1:]

b_v

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3265, 0.5816, 0.0918, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0204, 0.6122, 0.3673, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.2551, 0.7041, 0.0408, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0408, 0.7041, 0.2551, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.3673, 0.6224, 0.0102, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0918, 0.7449, 0.1633, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.5000, 0.5000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.1633, 0.7449, 0.0918, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0102, 0.6224, 0.3673, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.2551, 0.7041, 0.0408, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0408, 0.7041, 0.2551, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.3673, 0.6122, 0.0204],
        [0.0000, 0.0000, 0.0000, 0.000

In [132]:
control_points = control_points_flat.reshape((8,5,4)).permute(1, 0, 2)
control_points[0, :]

tensor([[ 0.0000,  0.0000, -1.0000,  1.0000],
        [ 0.0000,  0.0000, -1.0000,  0.7071],
        [ 0.0000,  0.0000, -1.0000,  1.0000],
        [ 0.0000,  0.0000, -1.0000,  0.7071],
        [ 0.0000,  0.0000, -1.0000,  1.0000],
        [ 0.0000,  0.0000, -1.0000,  0.7071],
        [ 0.0000,  0.0000, -1.0000,  1.0000],
        [ 0.0000,  0.0000, -1.0000,  0.7071]])

In [133]:
surface_4d = torch.einsum('iu, jv, uvw -> ijw', b_u, b_v, control_points)
surface_4d

tensor([[[ 0.0000,  0.0000, -1.0000,  1.0000],
         [ 0.0000,  0.0000, -1.0000,  0.8296],
         [ 0.0000,  0.0000, -1.0000,  0.8207],
         [ 0.0000,  0.0000, -1.0000,  0.9133],
         [ 0.0000,  0.0000, -1.0000,  0.9133],
         [ 0.0000,  0.0000, -1.0000,  0.8177],
         [ 0.0000,  0.0000, -1.0000,  0.7818],
         [ 0.0000,  0.0000, -1.0000,  0.8535],
         [ 0.0000,  0.0000, -1.0000,  0.9253],
         [ 0.0000,  0.0000, -1.0000,  0.8894],
         [ 0.0000,  0.0000, -1.0000,  0.7938],
         [ 0.0000,  0.0000, -1.0000,  0.7938],
         [ 0.0000,  0.0000, -1.0000,  0.8864],
         [ 0.0000,  0.0000, -1.0000,  0.8775],
         [ 0.0000,  0.0000, -1.0000,  0.7071]],

        [[-0.5556,  0.0000, -0.9444,  0.8535],
         [-0.5045, -0.3741, -0.9444,  0.7081],
         [-0.3515, -0.5442, -0.9444,  0.7005],
         [-0.1190, -0.5556, -0.9444,  0.7796],
         [ 0.1190, -0.5556, -0.9444,  0.7796],
         [ 0.3515, -0.5499, -0.9444,  0.6979],
         [ 

In [134]:
points_xyz = surface_4d[..., :3]
weights    = surface_4d[..., 3:]

surface_3d = points_xyz / weights
surface_3d

tensor([[[ 0.0000,  0.0000, -1.0000],
         [ 0.0000,  0.0000, -1.2053],
         [ 0.0000,  0.0000, -1.2185],
         [ 0.0000,  0.0000, -1.0949],
         [ 0.0000,  0.0000, -1.0949],
         [ 0.0000,  0.0000, -1.2230],
         [ 0.0000,  0.0000, -1.2791],
         [ 0.0000,  0.0000, -1.1716],
         [ 0.0000,  0.0000, -1.0808],
         [ 0.0000,  0.0000, -1.1243],
         [ 0.0000,  0.0000, -1.2598],
         [ 0.0000,  0.0000, -1.2598],
         [ 0.0000,  0.0000, -1.1281],
         [ 0.0000,  0.0000, -1.1397],
         [ 0.0000,  0.0000, -1.4142]],

        [[-0.6509,  0.0000, -1.1065],
         [-0.7125, -0.5284, -1.3337],
         [-0.5018, -0.7769, -1.3483],
         [-0.1527, -0.7126, -1.2115],
         [ 0.1527, -0.7126, -1.2115],
         [ 0.5036, -0.7879, -1.3532],
         [ 0.7561, -0.6966, -1.4153],
         [ 0.7625, -0.3813, -1.2963],
         [ 0.7034, -0.0502, -1.1958],
         [ 0.7318,  0.2614, -1.2441],
         [ 0.7865,  0.6108, -1.3940],
         [

In [135]:
vertices = surface_3d.reshape(-1, 3)
vertices

tensor([[ 0.0000,  0.0000, -1.0000],
        [ 0.0000,  0.0000, -1.2053],
        [ 0.0000,  0.0000, -1.2185],
        [ 0.0000,  0.0000, -1.0949],
        [ 0.0000,  0.0000, -1.0949],
        [ 0.0000,  0.0000, -1.2230],
        [ 0.0000,  0.0000, -1.2791],
        [ 0.0000,  0.0000, -1.1716],
        [ 0.0000,  0.0000, -1.0808],
        [ 0.0000,  0.0000, -1.1243],
        [ 0.0000,  0.0000, -1.2598],
        [ 0.0000,  0.0000, -1.2598],
        [ 0.0000,  0.0000, -1.1281],
        [ 0.0000,  0.0000, -1.1397],
        [ 0.0000,  0.0000, -1.4142],
        [-0.6509,  0.0000, -1.1065],
        [-0.7125, -0.5284, -1.3337],
        [-0.5018, -0.7769, -1.3483],
        [-0.1527, -0.7126, -1.2115],
        [ 0.1527, -0.7126, -1.2115],
        [ 0.5036, -0.7879, -1.3532],
        [ 0.7561, -0.6966, -1.4153],
        [ 0.7625, -0.3813, -1.2963],
        [ 0.7034, -0.0502, -1.1958],
        [ 0.7318,  0.2614, -1.2441],
        [ 0.7865,  0.6108, -1.3940],
        [ 0.6108,  0.7865, -1.3940],
 

In [141]:
fig = px.scatter_3d(vertices, x=0, y=1, z=2, color=weights.reshape(-1))
fig.show()

In [144]:
fig_u = px.imshow(b_u.cpu().numpy(), title="Matrice de Base U (Doit être une diagonale)", origin='lower')
fig_u.show()